services:
  - type: web
    name: flow-server
    env: node
    buildCommand: npm install --include=dev && npm run build -w shared && npm run build -w server
    startCommand: node server/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TURSO_CONNECTION_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        sync: false
